#!/usr/bin/env python3
"""Generate init.sql for the hardware support database from the product Excel.

Dev-only tooling: reads the normalized catalog workbook and emits a self-contained
init.sql (DDL + seed data) that the Postgres container loads automatically from
/docker-entrypoint-initdb.d. The container itself never depends on this script or
on openpyxl — only on the generated init.sql.

Source workbook (sheets used):
  - "Tablas Generales": technologies (A,B), product_lines (D,E,F),
    solutions (H,I,J,K) laid out side by side.
  - "Sample Products & Prices": the complete product+price sample
    (A=id, B=solution_id, C=family, D=name, E=variant, F=specification,
     G=material_number, H=typecode, I=price_ygdc).

Inventory is synthetic but deterministic (derived from the product id), since the
source data has no stock information. Run:

    python extract_from_excel.py [path/to/workbook.xlsx] [path/to/init.sql]
"""
from __future__ import annotations

import sys
from pathlib import Path

import openpyxl

# Default paths resolved relative to this script: scripts/ -> sql-database/ -> repo
SCRIPT_DIR = Path(__file__).resolve().parent
DEFAULT_XLSX = (
    SCRIPT_DIR.parents[2]
    / "Proyecto"
    / "Información"
    / "Database"
    / "Base de datos Productos Excel.xlsx"
)
DEFAULT_OUT = SCRIPT_DIR.parent / "init.sql"

CURRENCY = "EUR"  # YGDC is the Bosch Rexroth list-price column; assumed EUR for the MVP.


def sql_str(value) -> str:
    """Render a Python value as a SQL literal (NULL, number, or escaped string)."""
    if value is None or value == "-":
        return "NULL"
    if isinstance(value, (int, float)):
        return repr(value)
    return "'" + str(value).strip().replace("'", "''") + "'"


def synthetic_stock(pid: int) -> int:
    """Deterministic stock level (1..47) so seeds are reproducible across runs."""
    return (pid % 47) + 1


def synthetic_shelf(pid: int) -> str:
    """Deterministic warehouse shelf code derived from the product id."""
    aisle = chr(ord("A") + pid % 6)
    return f"{aisle}-{(pid // 100) % 20:02d}-{pid % 13:02d}"


def load_rows(xlsx_path: Path):
    wb = openpyxl.load_workbook(xlsx_path, data_only=True)

    tg = wb["Tablas Generales"]
    technologies, product_lines, solutions = [], [], []
    for r in range(2, tg.max_row + 1):
        if tg.cell(r, 1).value is not None:
            technologies.append((tg.cell(r, 1).value, tg.cell(r, 2).value))
        if tg.cell(r, 5).value is not None:  # product_lines: D=tech_id, E=id, F=name
            product_lines.append(
                (tg.cell(r, 5).value, tg.cell(r, 4).value, tg.cell(r, 6).value)
            )
        if tg.cell(r, 8).value is not None:  # solutions: H=id, I=line_id, J=name, K=desc
            solutions.append(
                (
                    tg.cell(r, 8).value,
                    tg.cell(r, 9).value,
                    tg.cell(r, 10).value,
                    tg.cell(r, 11).value,
                )
            )

    sp = wb["Sample Products & Prices"]
    products = []
    for r in range(2, sp.max_row + 1):
        if sp.cell(r, 1).value is None:
            continue
        products.append(
            {
                "id": sp.cell(r, 1).value,
                "solution_id": sp.cell(r, 2).value,
                "family": sp.cell(r, 3).value,
                "name": sp.cell(r, 4).value,
                "variant": sp.cell(r, 5).value,
                "specification": sp.cell(r, 6).value,
                "material_number": sp.cell(r, 7).value,
                "typecode": sp.cell(r, 8).value,
                "price": sp.cell(r, 9).value,
            }
        )
    return technologies, product_lines, solutions, products


def build_sql(technologies, product_lines, solutions, products) -> str:
    # Guard referential integrity so the seed never fails on orphan rows.
    tech_ids = {t[0] for t in technologies}
    product_lines = [pl for pl in product_lines if pl[1] in tech_ids]
    line_ids = {pl[0] for pl in product_lines}
    solutions = [s for s in solutions if s[1] in line_ids]
    sol_ids = {s[0] for s in solutions}
    products = [p for p in products if p["solution_id"] in sol_ids]

    out: list[str] = []
    out.append("-- Generated by scripts/extract_from_excel.py. Do not edit by hand.")
    out.append("-- Hardware support database: catalog hierarchy + prices + inventory.")
    out.append("BEGIN;")
    out.append("")
    out.append(
        "DROP TABLE IF EXISTS inventory, prices, products, solutions, "
        "product_lines, technologies CASCADE;"
    )
    out.append(
        """
CREATE TABLE technologies (
    id   INTEGER PRIMARY KEY,
    name TEXT NOT NULL
);

CREATE TABLE product_lines (
    id            INTEGER PRIMARY KEY,
    technology_id INTEGER NOT NULL REFERENCES technologies(id),
    name          TEXT NOT NULL
);

CREATE TABLE solutions (
    id          INTEGER PRIMARY KEY,
    line_id     INTEGER NOT NULL REFERENCES product_lines(id),
    name        TEXT NOT NULL,
    description TEXT
);

CREATE TABLE products (
    id              BIGINT PRIMARY KEY,
    solution_id     INTEGER NOT NULL REFERENCES solutions(id),
    family          TEXT,
    name            TEXT NOT NULL,
    variant         TEXT,
    specification   TEXT,
    typecode        TEXT UNIQUE NOT NULL,
    material_number TEXT UNIQUE NOT NULL
);
CREATE INDEX idx_products_typecode ON products (typecode);
CREATE INDEX idx_products_material ON products (material_number);
CREATE INDEX idx_products_solution ON products (solution_id);

CREATE TABLE prices (
    id         SERIAL PRIMARY KEY,
    product_id BIGINT NOT NULL REFERENCES products(id),
    price_ygdc NUMERIC(12, 2) NOT NULL,
    currency   TEXT NOT NULL DEFAULT 'EUR'
);
CREATE INDEX idx_prices_product ON prices (product_id);

CREATE TABLE inventory (
    id              SERIAL PRIMARY KEY,
    product_id      BIGINT NOT NULL REFERENCES products(id),
    stock_level     INTEGER NOT NULL DEFAULT 0,
    warehouse_shelf TEXT
);
CREATE INDEX idx_inventory_product ON inventory (product_id);
""".rstrip()
    )
    out.append("")

    out.append("-- technologies")
    for tid, name in technologies:
        out.append(
            f"INSERT INTO technologies (id, name) VALUES ({tid}, {sql_str(name)});"
        )
    out.append("")

    out.append("-- product_lines")
    for lid, tid, name in product_lines:
        out.append(
            "INSERT INTO product_lines (id, technology_id, name) "
            f"VALUES ({lid}, {tid}, {sql_str(name)});"
        )
    out.append("")

    out.append("-- solutions")
    for sid, lid, name, desc in solutions:
        out.append(
            "INSERT INTO solutions (id, line_id, name, description) "
            f"VALUES ({sid}, {lid}, {sql_str(name)}, {sql_str(desc)});"
        )
    out.append("")

    out.append("-- products")
    for p in products:
        # name is NOT NULL; a few source rows have an empty Nombre_Producto,
        # so fall back to the family or the typecode to keep it meaningful.
        name = p["name"] if p["name"] not in (None, "-", "") else (
            p["family"] or p["typecode"]
        )
        out.append(
            "INSERT INTO products (id, solution_id, family, name, variant, "
            "specification, typecode, material_number) VALUES ("
            f"{p['id']}, {p['solution_id']}, {sql_str(p['family'])}, "
            f"{sql_str(name)}, {sql_str(p['variant'])}, "
            f"{sql_str(p['specification'])}, {sql_str(p['typecode'])}, "
            f"{sql_str(p['material_number'])});"
        )
    out.append("")

    out.append("-- prices")
    for p in products:
        if p["price"] in (None, "-"):
            continue
        out.append(
            "INSERT INTO prices (product_id, price_ygdc, currency) "
            f"VALUES ({p['id']}, {p['price']}, {sql_str(CURRENCY)});"
        )
    out.append("")

    out.append("-- inventory (synthetic, deterministic from product id)")
    for p in products:
        pid = int(p["id"])
        out.append(
            "INSERT INTO inventory (product_id, stock_level, warehouse_shelf) "
            f"VALUES ({pid}, {synthetic_stock(pid)}, {sql_str(synthetic_shelf(pid))});"
        )
    out.append("")
    out.append("COMMIT;")
    out.append("")
    return "\n".join(out)


def main() -> int:
    xlsx_path = Path(sys.argv[1]) if len(sys.argv) > 1 else DEFAULT_XLSX
    out_path = Path(sys.argv[2]) if len(sys.argv) > 2 else DEFAULT_OUT
    if not xlsx_path.exists():
        print(f"ERROR: workbook not found: {xlsx_path}", file=sys.stderr)
        return 1

    technologies, product_lines, solutions, products = load_rows(xlsx_path)
    sql = build_sql(technologies, product_lines, solutions, products)
    out_path.write_text(sql, encoding="utf-8")
    print(
        f"Wrote {out_path} "
        f"({len(technologies)} technologies, {len(product_lines)} lines, "
        f"{len(solutions)} solutions, {len(products)} products)"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
