export const PRODUCTS = [
  {
    part_number: "6ES7214-1AG40-0XB0",
    product_name: "Siemens S7-1200 PLC",
    brand: "Siemens",
    category: "PLC",
    unit_price: 485.0,
    currency: "USD",
    stock_level: 12,
    warehouse_shelf: "A-14-03",
    specs: [
      "Compact PLC CPU 1214C DC/DC/DC with 14 digital inputs, 10 digital outputs, and 2 analog inputs.",
      "Integrated Profinet interface supports communication with HMI and SCADA systems.",
      "Programming via TIA Portal; supports LAD, FBD, STL, and SCL languages.",
    ],
  },
  {
    part_number: "25B-D4P0N104",
    product_name: "Allen-Bradley PowerFlex 525 VFD",
    brand: "Allen-Bradley",
    category: "VFD",
    unit_price: 612.5,
    currency: "USD",
    stock_level: 7,
    warehouse_shelf: "B-02-11",
    specs: [
      "Variable frequency drive rated 1.5 kW (2 HP), 480V AC three-phase input.",
      "Embedded EtherNet/IP communication for integration with ControlLogix and CompactLogix PLCs.",
      "Safe torque off (STO) capability; DIN rail or panel mount installation.",
    ],
  },
  {
    part_number: "EK1100",
    product_name: "Beckhoff EK1100 EtherCAT Coupler",
    brand: "Beckhoff",
    category: "I/O Coupler",
    unit_price: 295.0,
    currency: "USD",
    stock_level: 23,
    warehouse_shelf: "C-08-01",
    specs: [
      "EtherCAT bus coupler connecting up to 65,535 EtherCAT terminals to the bus.",
      "Supports Beckhoff TwinCAT automation software for configuration and diagnostics.",
      "DIN rail mount; status LEDs for link, activity, and error indication.",
    ],
  },
  {
    part_number: "LR-TB2000",
    product_name: "Keyence LR-TB2000 Distance Sensor",
    brand: "Keyence",
    category: "Sensor",
    unit_price: 349.99,
    currency: "USD",
    stock_level: 18,
    warehouse_shelf: "D-05-07",
    specs: [
      "Laser distance sensor with 0.05 to 2 m detection range and ±0.1% linearity.",
      "IP67-rated housing suitable for industrial environments with dust and moisture.",
      "Analog and discrete outputs; teach function for one-touch setup without tools.",
    ],
  },
];
